services:
    my_argv_aware_service:
        class: !require "../services/MyServiceArgvTest"
        arguments:
            - [] # Injected by ArgvCompilerPass
        tags:
            - 'argv.setter'
            - 'argv.constructor'

    single_argv_service:
        class: !require "../services/SingleArgvTest"
        arguments:
            - "@my_argv_aware_service"
            - "" # Injected by SingleArgvCompilerPass
            - "Title: %title%"
        tags:
            - 'argv.single'

    single_argv_service_2:
        class: !require "../services/SingleArgvTest"
        arguments:
            - "@my_argv_aware_service"
            - "" # Injected by SingleArgvCompilerPass
            - "Title: %title%"
        tags:
            - 'argv.single'

    auto_tag_collector:
        class: !require "../services/AutoTagCollector"
        arguments:
            - !tagged "argv.single"

    module_class_thing:
        class: !require ["../services/ModuleClassThing", "MyClass"]

    weird_arg_object:
        class: !require "../services/ComplexConstructor"
        arguments:
            - auto_tagged:
                - !tagged "argv.single"
                - !tagged "argv.constructor"
                - !tagged "argv.setter"
            - some_stuff:
                foo: 42
                param: "Title = %title%"
                service: "@single_argv_service_2"
            - "@module_class_thing"
